name: Tests

on:
  push:
    branches: [ main, master, e2e-relay-pinner ]
  pull_request:
    branches: [ main, master, e2e-relay-pinner ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_PRIVATE_KEY: 08011240821cb6bc3d4547fcccb513e82e4d718089f8a166b23ffcd4a436754b6b0774cf07447d1693cd10ce11ef950d7517bad6e9472b41a927cd17fc3fb23f8c70cd99
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        # cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Mocha tests
      run: |
       npm run build:relay
       npm run relay:test &
       RELAY_PID=$!
       trap "kill $RELAY_PID" EXIT
       sleep 10
       npx mocha "test/**/*.test.js"

    - name: Run e2e tests
      run: |
        npm run build:relay
        # Playwright config starts the Vite dev server, and globalSetup starts the relay.
        DEBUG=playwright:* npm run test:e2e
